### ISSUE TITLE
Implement onboarding screens

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#1]
Implement onboarding activity with 3 screens:

![page 1](https://user-images.githubusercontent.com/1358055/63537401-5529bc00-c51e-11e9-9948-7eb2f62640e9.png)

![page 2](https://user-images.githubusercontent.com/1358055/63537411-5b1f9d00-c51e-11e9-921f-3dd41a53e43e.png)

![page 3](https://user-images.githubusercontent.com/1358055/63537415-5d81f700-c51e-11e9-821d-d1436fe5da79.png)

Please use as a reference the onboarding section implemented for the old android app: https://github.com/code4romania/monitorizare-vot-android/pull/136

Figma wireframes available here: https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV-mobile?node-id=0%3A1

**Comment by AlexandraDaraban** [comment]
I'll work on this
