### ISSUE TITLE
Update menu to new UI

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#107]
Use the current MV logo.

Figma available here: https://www.figma.com/file/lww9lcabUpamTZg8zCExI8/MV-2.0-Prototype?node-id=26%3A161

![Menu](https://user-images.githubusercontent.com/1358055/67567006-c3af1400-f731-11e9-8dff-9d0b6a42aa4f.png)

**Comment by AlexandraDaraban** [comment]
I'll work on this
