### ISSUE TITLE
Add settings screen

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#112]
Texts and images are still TBD.

It should include:
- about info for the app
- possibility to change the app language
- possibility to send feedback email

Figma available here: https://www.figma.com/file/lww9lcabUpamTZg8zCExI8/MV-2.0-Prototype?node-id=26%3A161

![Settings](https://user-images.githubusercontent.com/1358055/67567736-1d640e00-f733-11e9-87fe-4503622c3303.png)

**Comment by AndreiMares** [comment]
Hey there Aniri.
I would like to make this screen but i have a question regarding "Conecteaza-te" button. Where should i redirect the user: inside in our app to another screen or outside (default email app)?
Can you add me to code4romania slack channel ?:D Email:andrei.mares06@gmail.com.
Thank you:)

**Comment by aniri** [comment]
Hey @AndreiMares ! Thanks for your interest :smile:

The UI and content for this screen is not yet final, but I can list the items that we need and it would be great if you could implement the layout & basic setup for it.

- app version & code 4 romania logo (they are now present only in the login screen) :point_up:
- a title + paragraph of text :point_up:

and the following actions (the UI looks good for this part):

- the change language action - should redirect the user to the language picker screen (it is now a part of onboarding)
- the contacteaza-ne action - should open the email client picker for the user to send feedback via email. the contact email address should be stored in the properties file. :point_up:
- a 'view privacy policy' action - a link that would open a browser window. the privacy policy link should be stored in the properties file :point_up:

The ones with :point_up: have higher priority :)
