### ISSUE TITLE
Push notifications - send fcm token

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#15]
After a successful login, send the fcm token to the backend app.

Please see related endpoint from BE:
`BE_URL/api/v1/notification/register?ObserverId=1&ChannelName=Firebase&Token=sfgasdgasdgsd`

Swagger for new BE API is available here: http://mv-mobile-test.azurewebsites.net/swagger/index.html

**Comment by RaduCStefanescu** [comment]
The BE should implement a new controller for push notifications, with a new endpoint:
POST /api/v1/notification
The object sent as part of the post request should contain the fcm token.

**Comment by RaduCStefanescu** [comment]
https://github.com/code4romania/monitorizare-vot/issues/125

**Comment by AlexandraDaraban** [comment]
I will work on this.
