### ISSUE TITLE
Push notifications - display received push notifications

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#16]
We will add firebase push notifications to the app.

If a push notification is received while the app is open, display the received push notification info in a dialog. The push notification will only contain some text. The dialog should display the text from the notification and an 'ok' button.

**Comment by RaduCStefanescu** [comment]
https://github.com/code4romania/monitorizare-vot/issues/126

**Comment by gauravrai1** [comment]
@aniri I am interested to work on this, can you elaborate the task a bit?

**Comment by aniri** [comment]
> @aniri I am interested to work on this, can you elaborate the task a bit?

@ThinkHattke Thanks for offering to help with this! :smile: 

I have added a bit more info to the issue details. Please let me know if you have other questions.

**Comment by gauravrai1** [comment]
@aniri I have gone through the details and started working on it, will send a pr once completed. thank you :)

**Comment by aniri** [comment]
@ThinkHattke Hey :) Any news? Did you get the chance to work on this? Thanks!
