### ISSUE TITLE
[Improvement][Push notifications] Display the received notification in app when the user opens the app by pressing on a received notification

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#160]
Current behaviour:
- user has the app closed and receives a push notification that is displayed in the top bar
- the user clicks on the notifications
- the MV app is opened

Expected behaviour:
- user has the app closed and receives a push notification that is displayed in the top bar
- the user clicks on the notifications
- the MV app is opened
- **the notification is displayed in a dialog (same dialog as for the notifications received when the app is opened)**

**Comment by sergiuciuperca** [comment]
Hi. I will fix this.

**Comment by aniri** [comment]
@sergiuciuperca hey! did you make any progress on this?

**Comment by sergiuciuperca** [comment]
Hi @aniri. I've created #165. Please let me know there if other changes should be added

**Comment by aniri** [comment]
hey @sergiuciuperca the PR looks good! but I think it would be safer to just display to notification in the splash screen and only continue navigating to the MainActivity after clicking the Ok button in the dialog. This way, the notification is also shown if the user is logged out.

**Comment by sergiuciuperca** [comment]
@aniri  fixed :)
