### ISSUE TITLE
[Improvement] Show the 'has notes' icon for questions also in the question details screen

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#161]
Currently an icon is displayed in the questions list, for the questions that have notes on them. Display the icon also in the question details screen.

Also, investigate if the 'Adauga o note la intrebare' text should be changed if the question already has some notes added.

**Comment by CatalinPrata** [comment]
I would like to start working on this, can someone assign it to me?

About the second thing, I suggest to change the text to: "Vezi/adauga note la intrebare"  
And when there is no note added, we can leave it as it is now. 

Any thoughts on this?

**Comment by aniri** [comment]
@CatalinPrata hey! yes, the text improvement suggestion sounds great! could you also include it in the fix?
