### ISSUE TITLE
Add the possibility of changing the app language from the about screen

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#166]
The UI setup is done, but commented out for now.

Clicking the 'change language' option from the about screen should open the language picker screen and allow the user to change the app language.

The language picker screen is part of the onboarding process now. Please reuse as much of that code and language changing logic as possible.

**Comment by lukstbit** [comment]
Hey, I implemented this with a BottomSheetDialogFragment as a quick option for the user to change the language. It uses some of the code from the onboarding screen(which I refactored in two methods).

Example UI

![screenshot](https://user-images.githubusercontent.com/52494258/71911483-6cd7a900-317c-11ea-89b9-8b38bb7199bb.png)
