### ISSUE TITLE
Add analytics to about screen

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#169]
- log screen name: "About"
- log clicks on actions

**Comment by sebigansca** [comment]
Lucrez eu la asta :)

**Comment by aniri** [comment]
@sebigansca salut! ai vreun update pe issue? :smile:

**Comment by sebigansca** [comment]
Servus, 
imi cer scuze ca n-am apucat sa il finalizez, am facut push la mine dar as vrea sa mai fac niste mici modificari, cel tarziu weekend-ul asta si fac PR.

**Comment by aniri** [comment]
@sebigansca super! mersi! :tada:

**Comment by sebigansca** [comment]
PR created: https://github.com/code4romania/mon-vot-android-kotlin/pull/182
