### ISSUE TITLE
[Bug] Incorrect arrival vs leaving time check

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#173]
This bug was reported by only one observer. Please investigate.

![Capture](https://user-images.githubusercontent.com/1358055/69499142-b2575400-0ef7-11ea-8535-97645d3defd8.JPG)

**Comment by ssand** [comment]
Tested the master branch code (v2.0.7-b35) on 3 devices:
- Nexus 5, Android 6.0.1
- Huawei P9 Lite, Android 7.0
- Samsung Galaxy Note 3, Android 5.1.1
Couldn't reproduce the issue on any of the devices.

**Comment by aniri** [comment]
@ssand thanks for checking! I will close this issue as it cannot be reproduced!
