### ISSUE TITLE
[Improvement] Add toggle to switch between visible / hidden password characters on login screen

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#174]

**Comment by sebigansca** [comment]
I will take this one!

**Comment by aniri** [comment]
hey @sebigansca :smile: any news on this one?

**Comment by lukstbit** [comment]
Thanks to [material design](https://material.io/develop/android/components/text-input-layout/) we only need to add two attributes in the xml layout. If there aren't extra requirements my pull implements this. Hope this is ok with @sebigansca
