### ISSUE TITLE
Uploading image as note, not possible from certain folders

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/mon-vot-android-kotlin#178]
In the mobile app on an Android phone, while adding a note, it is not possible to upload any image from the folders highlighted in red in the following screenshot. Moreover, selecting an image from the Download section actually crashes the app. The impact is not major as in most of the cases the user will just upload an image recently taken with his/her phone and this will be in one of the accessible folders.
![Upload_image](https://user-images.githubusercontent.com/56204138/69979654-5d3ec200-1537-11ea-8b15-91655ef81c37.jpg)

**Comment by aniri** [comment]
@gepaltineanu hey :) could you please give us more details about the device model you are testing on and also about the android version used? thanks!

**Comment by gepaltineanu** [comment]
Hi :) 
Testing was done on Samsung S10 plus, android version 9.

**Comment by aniri** [comment]
useful link: https://developer.android.com/about/versions/11/privacy/storage
