### ISSUE TITLE
Display observers guide when the user selects the action from the menu

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#18]
Please use the same display method as the old app:  https://github.com/code4romania/monitorizare-vot-android

The url for the observers guide should be extracted in a config file.

**Comment by danielberbece** [comment]
Hi! I want to help you on this issue. Is it ok?

**Comment by aniri** [comment]
@danielberbece hey! this issue is already in progress, please check the ones that are marked as to do :smiley:
