### ISSUE TITLE
Combine the login and send fcm token in one api call

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#190]
Send the firebase token on the login call. There is no need for two separate calls.

Use the new login endpoint:
`POST ​/api​/v2​/access​/authorize`

Send both login info & firebase related info:
```
{
  "user": "string",
  "password": "string",
  "channelName": "string",
  "fcmToken": "string"
}
```

Remove the call to `POST ​/api​/v1​/notification​/register`

**Comment by pedrofsn** [comment]
@aniri if you need more help, let me know! 

#hacktoberfest

**Comment by aniri** [comment]
hey @pedrofsn thanks for your contribution! :rocket: 

We do have some other issues we need help with:
- https://github.com/code4romania/mon-vot-android-kotlin/issues/100
- a bug that needs more investigation: https://github.com/code4romania/mon-vot-android-kotlin/issues/177
