### ISSUE TITLE
Load menu links from remote configs

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#212]
The following links were added in firebase remote configs so we can easily update them:
- `observer_guide_url`
- `safety_guide_url`

When opening the app, attempt to load the info from remote configs and only use the values from the properties files as backup.

Also, please hide the safety menu item in case the `safety_guide_url` value is missing from both the properties file and the remote config.

**Comment by DeKaN** [comment]
Can I take this issue?

**Comment by aniri** [comment]
> Can I take this issue?

sure! thanks @DeKaN
