### ISSUE TITLE
Sort form sections, questions and options by OrderNumber

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#218]
The new `OrderNumber` field is returned by the API. It should be used to sort the form data (form sections, for questions and options for questions) :)

**Comment by pedrofsn** [comment]
I didn't find this class. 
I could help in this task.

**Comment by aniri** [comment]
> I didn't find this class.
> I could help in this task.

@pedrofsn thanks for your interest, but this task is already fixed in a PR waiting for review :smiley:
