### ISSUE TITLE
Double check that unsynced data is searched in all locally stored data

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#220]
If there are unsynced answers, notes or polling stations infos, the manual sync button is shown.

Please double check that this happens even if the unsynced data is not from the currently opened polling station, but from any of the others as well.

**Comment by lukstbit** [comment]
Are there reports of the sync button not being shown when it should?

**Comment by aniri** [comment]
@lukstbit there was one reported occasion, but I'm not sure how accurate the report was, so we just need to double check.

The thing is: the users of the app fill out forms (answer questions and send notes) from different polling stations. The `manual sync` button shows up when there are unsynced answers, notes or polling station info. In one occasion it seemed to not show up when the user changed the polling station, but they had unsynced answers from the previous polling station.

**Comment by lukstbit** [comment]
I've looked at this and didn't found anything suspicious. I guess there could be some race conditions that could lead to this but with one report and no steps to reproduce it would be impossible to fix. And a restart of the app will allow the user to continue anyway.

**Comment by aniri** [comment]
@lukstbit yep, I couldn't reproduce it either :)

**Comment by aniri** [comment]
closing this as it cannot be reproduced
