### ISSUE TITLE
Add fastlane, build/versioning settings and analytics and crashlytics configs from old app

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#23]
Copy the configs from the old app: https://github.com/code4romania/monitorizare-vot-android

**Comment by aniri** [comment]
fastlane added by https://github.com/code4romania/mon-vot-android-kotlin/pull/35 , the rest should also be imported

**Comment by faogustavo** [comment]
@aniri I'm doing it here. Are the flavors still necessary?
