### ISSUE TITLE
[Bug] Notes icon is displayed if question with same Id from different polling station has notes

### ISSUE THREAD

**Issue by cipick** [code4romania/mon-vot-android-kotlin#250]
If you add a note to question B1 the note icon and see notes history text will be displayed for the same question in all polling stations.

Steps to reproduce:
1. Add note to question B1 in polling station 1
2. Create new polling station 2
3. Go to question B1 and notice the notes icon even if you didn't have any notes.

**Comment by lukstbit** [comment]
Thank you for the bug report, the notes icon indeed is shown when it shouldn't. I made a PR which will fix this.
