### ISSUE TITLE
Add the possibility of uploading more than one photo for a note

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#28]
Please use the new `POST ​/api​/v2​/note` endpoint that accepts multiple files upload for notes.

**Comment by RaduCStefanescu** [comment]
https://github.com/code4romania/monitorizare-vot/issues/127

**Comment by lukstbit** [comment]
The changes for the new version of the notes endpoint makes uploading notes to the current endpoint used by the app(_https://api.votemonitor.org/api/v2/note/upload_) to fail with a 500 error. So fixing the old endpoint or implementing this feature in the app is critical.

**Comment by aniri** [comment]
> The changes for the new version of the notes endpoint makes uploading notes to the current endpoint used by the app(_https://api.votemonitor.org/api/v2/note/upload_) to fail with a 500 error. So fixing the old endpoint or implementing this feature in the app is critical.

@lukstbit oh, thanks for letting us know. We have to do both :D I'll add a bug on the backend app in order to fix the old endpoint. But it would be awesome to be able to use the new one in the app so users could add more than one photo :)

**Comment by aniri** [comment]
@lukstbit the old endpoint is working well now :)

**Comment by lukstbit** [comment]
Yes, it is! I'll look over uploading notes with multiple files over the weekend.
