### ISSUE TITLE
Add voting section details header

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#29]
All screns should display the header with the info about the current voting section.

There should be an option to change the voting section -> the voting section details will be filled in for the new section: https://github.com/code4romania/mon-vot-android-kotlin/issues/7

Figma wireframes are available here: https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV-mobile?node-id=0%3A1

Please use as reference the old android app: https://github.com/code4romania/monitorizare-vot-android

TBD: should the end time be saved automatically when changing stations?

**Comment by AlexandraDaraban** [comment]
I will work on this
