### ISSUE TITLE
Splash screen + auth session management

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#31]
- add splash screen to app
- check if an auth token was already stored in shared preferences
    - if it doesn't have a token -> open login screen
    - if it does have a token -> skip login screen
- when the user selects the logout option from the menu, the token should be deleted from shared preferences

**Comment by danielberbece** [comment]
I want to help on this issue. Is there a splash screen design?

**Comment by aniri** [comment]
@danielberbece there is no specific design for it. you can use the same background image as for the login screen :smiley:

**Comment by danielberbece** [comment]
Ok, I will start working on this then! :)
