### ISSUE TITLE
[Bug] Fix county spinner

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#32]
When you login for the first time, the spinner automatically selects the first entry in the list. 

Correct behaviour: no option should be selected.

**Comment by sergiuciuperca** [comment]
Hi, I would like to work on this issue.

As it will be my first contribution - I was unable to find any test credentials for login. It is there any related documentation?

**Comment by aniri** [comment]
@sergiuciuperca please use the following test account: 0722222222 123456
