### ISSUE TITLE
Lists optimizations

### ISSUE THREAD

**Issue by AlexandraDaraban** [code4romania/mon-vot-android-kotlin#45]
When something is updated in the database, the list's adapter should request changes only for the updated items.

**Comment by DeKaN** [comment]
Hi, I would like to work on issue.
I can write a solution via ListAdapter (it updates only changed items).

By the way, I see you use "item view types" for RecyclerView adapter. Can I [use](https://github.com/sockeqwe/AdapterDelegates) this library for improving code?

**Comment by AlexandraDaraban** [comment]
Hi, sounds good. Go for it
