### ISSUE TITLE
Implement buttons states

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#47]
- Choose polling station screen: 'continue' button should be enabled only if the county and polling station number are filled in
- Polling station details screen: 'continue to forms' button should be enabled only if the area, president and arrival time info are filled in
- Notes Screen: the send note button should be enabled if the user added some text

![buttons](https://user-images.githubusercontent.com/1358055/66227214-64875200-e6e5-11e9-9cbd-5bd82ee225aa.jpg)

complete UI in figma: https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV---mobile

**Comment by Talisantos** [comment]
I will work on this issue

**Comment by pr0t3us** [comment]
I would like to take care of this task.

**Comment by pr0t3us** [comment]
@aniri need some help with
>the sync data manually button should be enabled only if there are unsynced answers or notes

as I understand it should be done in `FormsListFragment`, do you know how to get the list of unsynced answers/notes?

**Comment by aniri** [comment]
@pr0t3us I have updated the issue info as the behavior of the sync data manually button is a bit different and should not be included in this task :smile:

**Comment by pr0t3us** [comment]
>login button should only be enabled when phone number and code where added

I see this is also removed from requirements.

**Comment by aniri** [comment]
@pr0t3us yes, it was also removed. since that button look a bit different from the others.
