### ISSUE TITLE
[Analytics] Log event when user clicks the manual sync button

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#49]
- send the number of unsynced items to analytics

**Comment by mrwhoknows55** [comment]
@aniri can you please give some more info?

**Comment by aniri** [comment]
@mrwhoknows55 sure :smiley: 

The app works like this: the users visit one of more polling stations and fill out the same forms for each of them. There is a possibility that the users will have limited or no internet access, in which case the answers are stored locally. If there are unsynced items, the `manual sync` button is shown to the user and they can use it when they get to a better internet connection. We have logged this click to analytics , but it would be helpful to have some idea about how many unsynced items they usually have. This happens in `FormsListFragment` : `logAnalyticsEvent(Event.MANUAL_SYNC, Param(ParamKey.NUMBER_NOT_SYNCED, 0))` . It would be great if we could get a count of unsynced items and send it to analytics. We should count at least the unsynced answers, but preferably all unsync answers, notes and polling station info (just the total could of not synced db entries).

**Comment by lukstbit** [comment]
@aniri I've taken the liberty to implement this feature.
