### ISSUE TITLE
Update titles in action bar

### ISSUE THREAD

**Issue by AlexandraDaraban** [code4romania/mon-vot-android-kotlin#65]
For the following screens the title displayed should be as stated below:
- choosing the polling station: `Choose your polling station`
- filling the polling station's details: `Polling station details`
- the observer's guide: `Observer's guide`
- list of screens: `Forms`
- list of questions for a form: form description (e.g: for the `A` form the title displayed should be `A - Deschidere`)
- add a note: `Notes`
Figma: https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV---mobile?node-id=5%3A57

**Comment by IvanSantosGonz** [comment]
I can do this

**Comment by AlexandraDaraban** [comment]
Thank you for your interest but, unfortunately, the the specifications still need to be discussed and are not final yet. Therefore the issue can't be developed at the moment. But we still need help with other issues :D

**Comment by IvanSantosGonz** [comment]
ok

**Comment by AlexandraDaraban** [comment]
I'll work on this
