### ISSUE TITLE
[Bug] `Add photo or video` button does nothing if permission denied

### ISSUE THREAD

**Issue by AlexandraDaraban** [code4romania/mon-vot-android-kotlin#73]
**Current**: App doesn't have the storage permission. User taps on `Add photo or video` button and user is prompted to give permission to storage. User denies it and taps on `Add photo or video` button again. Nothing happens.
**Expected**:  App doesn't have the storage permission. User taps on `Add photo or video` button and user is prompted to give permission to storage. User denies it and taps on `Add photo or video` button again. **The user should be prompted again to give permission to storage. If the user denies it permanently, when user taps again the button, he should be redirected to app settings to grant access from there**

**Comment by gTisca** [comment]
I can take it. Do you have any suggestions regarding the message which we should show before redirecting the user to Settings?
Something like: 

> For using this function you have to change the app permissions. Please open the Settings menu and grant access to the requested permissions.

**Comment by AlexandraDaraban** [comment]
Hi, @gTisca. The text is ok. We will go through all the strings anyway before uploading to store in order to make sure they are consistent and properly translated so don't worry about that.
