### ISSUE TITLE
[Bug] Navigation issue

### ISSUE THREAD

**Issue by AlexandraDaraban** [code4romania/mon-vot-android-kotlin#74]
**Current**: The forms list is displayed. The user opens the menu and goes to observer's guide. The observer's guide is displayed. User taps back and the forms list is displayed. The user opens the menu and the observer's guide is still selected.
**Expected**: The forms list is displayed. The user opens the menu and goes to observer's guide. The observer's guide is displayed. User taps back and the forms list is displayed. The user opens the menu and **the forms item is selected.**

<p align="center">
<img src="https://user-images.githubusercontent.com/7293104/66652840-56828580-ec3f-11e9-926d-42bafe8ef25b.png" height=700>
</p>

**Comment by danielberbece** [comment]
I can take a look :)

**Comment by danielberbece** [comment]
I haven't found a solution. Instead, we could drop the highlight completely. What do you think?

**Comment by aniri** [comment]
> I haven't found a solution. Instead, we could drop the highlight completely. What do you think?

@danielberbece We should keep the current screen as highlighted in the menu so we won't confuse the users :smile:

**Comment by danielberbece** [comment]
Ok, I will try to find a workaround

**Comment by AlexandraDaraban** [comment]
Hey, @danielberbece. Did you find any solution yet? 😄

**Comment by danielberbece** [comment]
I haven't found a solution yet. Do you have any suggestions?

**Comment by AlexandraDaraban** [comment]
We don't have a solution at the moment but thank you for trying to help. We will try to find a workaround in the future, but we have other tasks you can help us with so you won't be stuck on this.  😄
