### ISSUE TITLE
[Bug] Missing warning message when selecting an invalid section

### ISSUE THREAD

**Issue by AlexandraDaraban** [code4romania/mon-vot-android-kotlin#76]
**Current**: When selecting a a voting section, the user selects a county and completes an invalid polling section number. When the user taps the`Continue` button, nothing happens.

**Expected**: When selecting a a voting section, the user selects a county and completes an invalid polling section number When the user taps the`Continue` button, **a toast with a message error should appear.** 

This doesn't work fine because the message event is triggered in the `parentViewModel` which is attached to the `activity` so the solution would be to listen to the error in the `BaseActivity`

**Comment by sergiuciuperca** [comment]
Hi. I will fix this
