### ISSUE TITLE
Implement link states

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#78]
Update the appearance of the links in the app. Add the tapped state as shown bellow. 

Links from app:
- Question screen: add note to current question
- Notes Screen: add photo video link

![buttons](https://user-images.githubusercontent.com/1358055/66227214-64875200-e6e5-11e9-9cbd-5bd82ee225aa.jpg)

complete UI in figma: https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV---mobile

**Comment by AlexandraDaraban** [comment]
Closed by #115
