### ISSUE TITLE
Implement notes fragment

### ISSUE THREAD

**Issue by aniri** [code4romania/mon-vot-android-kotlin#9]
Implement the fragment for notes. Available actions:
- add a new note -> notes will be stored locally in db and synced with backend
- view the list of previously sent notes -> this should be retrieved from local db
- it should be possible to upload/take a photo/video and send it with the note

Figma wireframes are available here: https://www.figma.com/file/21x1ui3YZJrGnpZNVnEuuQ/DRAFT-MV-mobile?node-id=0%3A1

Please use as reference the old android app: https://github.com/code4romania/monitorizare-vot-android

TBD: should this be a separate activity, or part of the main one?
TBD: what happens when you click on an old note?

**Comment by RaduCStefanescu** [comment]
The required BE endpoint should be:
GET /api/v1/note
Based on the token information, we query for the notes of the user and return them as a list of objects.

**Comment by RaduCStefanescu** [comment]
Linked issue: https://github.com/code4romania/monitorizare-vot/issues/124

**Comment by aniri** [comment]
![notes1](https://user-images.githubusercontent.com/1358055/66227140-3ace2b00-e6e5-11e9-9314-b99f6de5f7de.jpg)

![notes2](https://user-images.githubusercontent.com/1358055/66227141-3ace2b00-e6e5-11e9-852f-558ab369f271.jpg)

![notes3](https://user-images.githubusercontent.com/1358055/66227142-3b66c180-e6e5-11e9-9798-d24fa3ed1fe8.jpg)
